### ISSUE TITLE
Cannot pass BigNumber to Contract constructor parameter

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-hardhat-hethers#27]
### Description

`BigNumber` variables cannot be passed to constructor params(and though untested possibly function params as well). `number` variables work fine. The error that is thrown is:
```
Error: missing argument:  in Contract constructor (count=2, expectedCount=3, code=MISSING_ARGUMENT, version=contracts/1.2.0)
```

### Steps to reproduce

```
const ERC20 = await hre.hethers.getContractFactory("ERC20Mock", accounts[0]);

// number works:
await ERC20.deploy(`Token A`, `TOKENA`, 1_000_000))

// BigNumber fails:
const supply = BigNumber.from(1_000_000).mul(BigNumber.from(10).pow(0));
await ERC20.deploy(`Token A`, `TOKENA`, supply))

// Using BigNumber.toString() works:
const supply = BigNumber.from(1_000_000).mul(BigNumber.from(10).pow(0)).toString();
await ERC20.deploy(`Token A`, `TOKENA`, supply))
```

### Hedera network

other

### Version

1.0.2

### Operating system

macOS

**Comment by Kalina-Todorova** [comment]
The fix will most probably be in hethers.js

**Comment by mshakeg** [comment]
@Kalina-Todorova I initially created [the issue there](https://github.com/hashgraph/hethers.js/issues/275), I suppose it makes more sense to have it there since the issue is with hethers
