### ISSUE TITLE
Return type of deploy contract doesn't match contract type

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-hardhat-hethers#29]
### Problem

The only allowed return type of the deployed contract is `Contract`, however, the type of the deployed contract should also be allowed.
```
const ERC20Factory = await hre.hethers.getContractFactory("ERC20", accounts[0]);

// works fine
const erc20contract1: Contract = await ERC20Factory.deploy(`Token A`, `TOKENA`, 1_000_000);

// type error:
// Type 'Contract' is missing the following properties from type 'ERC20': DOMAIN_SEPARATOR, allowance, approve, balanceOf, and 11 more.
const erc20contract2: ERC20 = await ERC20Factory.deploy(`Token A`, `TOKENA`, 1_000_000);
```

### Solution

- the return type of `hethers.ContractFactory.deploy` should allow for both hethers.Contract or type of Contract which is identical to the contract name.

**Comment by natanasow** [comment]
@mshakeg It's not reproducible on my side. Could you provide more context? And do you use the latest version?

**Comment by mshakeg** [comment]
Hi @natanasow this was a while back but I think it was a ts cast issue, I haven't tested it with hethers, but with hre.ethers the following would work:
```
const erc20: ERC20 = (await ERC20Factory.deploy(`Token A`, `TOKENA`, 1_000_000)) as ERC20;

// type issue:
const erc20: ERC20 = await ERC20Factory.deploy(`Token A`, `TOKENA`, 1_000_000);
```
So if that works in hethers as well then this issue can be closed

**Comment by natanasow** [comment]
I've tested it with both `ethers` and `hethers` and it works, so I'm closing the issue.
