### ISSUE TITLE
new release with latest dependencies

### ISSUE THREAD

**Issue by mshakeg** [hashgraph/hedera-hardhat-hethers#38]
### Problem

`@hashgraph/hardhat-hethers@1.0.3` has dependency `@hashgraph/hethers@1.1.0` which in turn has dependency `@hashgraph/sdk@2.11.0-beta.1`, this causes a few issues which would be resolved with a new `@hashgraph/hethers` release(X) that points to the latest SDK and then also another release for `@hashgraph/hardhat-hethers` which points to the (X)

### Solution

- See above.

**Comment by mshakeg** [comment]
Hi @Kalina-Todorova , can you please allocate resources to this? It's a pretty simple ask and shouldn't take more than an hour.

I have `@hashgraph/hardhat-hethers` and `@hashgraph/hethers` installed in a project which installs `@hashgraph/sdk@2.11.0-beta.1` which results in a few issues in setting the stake to node or stake to account functionality that was introduced in a later version of the `@hashgraph/sdk`.

**Comment by georgi-l95** [comment]
Hey @mshakeg , thanks for bringing this up. We'll move it up the priority list.

**Comment by georgi-l95** [comment]
Hey @mshakeg , checkout new release.
